[package]
name = "biotoxin495/dropdown"
description = "An efficient dependency-free dropdown UI creator and controller for Roblox."
version = "1.0.2"
license = "MIT"
authors = ["biotoxin495"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/biotoxin495/Dropdown"

exclude = [
	"examples",
	"docs",
	".github",
	"*.rbxl",
	"*.rbxlx",
]

[dependencies]
Signal = "sleitnick/signal@2.0.3"